<?php echo var_dump($this->out);?>
<div class="container" align="center">
    <h2>Control alumnos</h2><hr>
    <div id="accordion">

    <div align="right">
        <!-- Ir a pantalla de DAR DE ALTA -->
        <a href="" target="_self"> <input type="button" class="btn btn-primary" name="boton" value="Agregar" /> </a>
        <!-- Regresar a pantalla anterior -->
        <a href="" target="_self"> <input type="button" class="btn btn-danger" name="boton" value="Cancelar" /> </a>
    </div>
</div>
