<script>
  $(document).ready(function(){
    $('.btn-link').click(function(){
      console.log(this.id);
      //$('#id-eliminar').val(this.id)
      window.location = "http://projectzend.localhost/Alumnos/delete?q="+this.id;
    });
    $('.btn-warning').click(function(){
      console.log(this.id);
      window.location = "http://projectzend.localhost/Alumnos/formupdate?q="+this.id;
    })
  });
</script>
<div class="container" align="center">
  <h2 id="id_alumno_head">Lista de Alumnos</h2>
  <div id="accordion">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Grado</th>
          <th>Fecha de nacimiento</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->out["data"] as $datosAlumnos): ?>
          <tr>
            <td>
              <?php echo $datosAlumnos['id_alumno']?>
            </td>
            <td>
              <?php echo $datosAlumnos['nombre']." ".$datosAlumnos['ap_pat']." ".$datosAlumnos['ap_mat'];?>
            </td>
            <td>
              <?php echo $datosAlumnos['grado'];?>
            </td>
            <td>
              <?php echo (date("d-m-Y", (strtotime($datosAlumnos['fecha_nacimiento']))));?>
            </td>
            <td>
              <button class="btn btn-link" id="<?php echo $datosAlumnos['id_alumno']?>">Eliminar</button>
            </td>
            <td>
              <button class="btn btn-warning" id="<?php echo $datosAlumnos['id_alumno']?>">Modificar</button>
            </td>
          </tr>
        <?php endforeach;?>
      </tbody>
    </table>
    <div align="right">
      <!-- Ir a pantalla de DAR DE ALTA -->
      <a href="add" target=""> <input type="button" class="btn btn-primary" name="boton" value="Agregar" /> </a>
        <!-- Regresar a pantalla anterior -->
      <a href="" target="_self"> <input type="button" class="btn btn-danger" name="boton" value="Cancelar" /> </a>
    </div>
  </div>
</div>
