<html xmlns="http://www.w3.org/1999/xhtml" lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Escuelita-Zend</title>
  <?php echo $this->headScript()->appendFile('/js/bootstrap.min.js', 'text/javascript')
                                ->prependFile("/js/jquery.js", 'text/javascript')
                                ->prependFile("/jquery-ui/jquery-ui.js")?>
  <?php echo $this->headLink()->prependStylesheet('/css/bootstrap.min.css') ?>
  <?php echo $this->headLink()->prependStylesheet('/jquery-ui/jquery-ui.css') ?>

</head>
<?php echo $this->layout()->content ?>
</body>
</html>
